
/**
 * Per FF-3 (Gate F): Simplified-Chinese node DESCRIPTION bodies, parallel to
 * `nodeTextZh` (which only translates node NAMES). Covers the
 * spacex_reusable_launch + humanoid_robotics domains so the rail core-judgment
 * (核心判断) body renders Chinese instead of splicing the English
 * `description` into a zh sentence. Lookup falls back to the English
 * description when an id has no zh entry. Source map:
 * .scratch/zh-descriptions.json (260 entries).
 */
const nodeDescriptionZh: Record<string, string> = {
  "launch_tvc_actuators_merchant": "为运载火箭发动机喷管摆动以实现矢量控制的机电 / 电液 / 电静液作动器。在 SpaceX 发动机上这一功能为自研封闭：Merlin 采用由发动机自身 RP-1 涡轮泵压力驱动的液压活塞，而 Super Heavy 的可摆动 Raptor 在 Starship 首飞后由液压切换为自研电动作动系统。真正的商用 TVC 作动器层（Moog、Woodward）飞行于其他型号（ULA Vulcan/Centaur、Antares、SLS 级上面级），而非 SpaceX 发动机核心。",
  "launch_propellant_pneumatic_valves_merchant": "用于运载火箭发动机及级段流体系统的低温兼容推进剂与增压介质控制阀（球阀、提升阀、先导式）、发动机控制阀以及气动 / 伺服阀。商用供应商（Moog、Woodward、Parker Aerospace、Eaton）向整个发射行业供货；SpaceX 为 Merlin/Raptor 大量自研阀门，但更广义的可回收发射行业仍依赖这一商用层。",
  "launch_engine_igniter_merchant": "点燃液体火箭发动机主燃烧室及预燃室 / 燃气发生器的火花-火炬 / 增强火花点火器。SpaceX 在 Merlin 上使用自研火炬点火器，在 Raptor 上使用火花点火系统；未发现向 SpaceX 供货的公开商用点火器供应商。该部件被记录为在 SpaceX 真正自研封闭，对可回收发射主承包商而言公开商用层薄弱 / 几乎缺失。",
  "launch_engine_precision_bearings_merchant": "用于运载火箭发动机涡轮泵、万向节 / 推力矢量关节及级段机构的精密滚动轴承、球面轴承与低温自润滑轴承。商用轴承厂商（RBC Bearings，其 FibriloidCR 低温轴承在运载火箭应用中已飞行验证；舍弗勒 Schaeffler；斯凯孚 SKF）服务于这一层；SpaceX 发动机涡轮泵内部轴承未公开外采，很可能为自研 / 定制。",
  "launch_engine_metal_am_machines_merchant": "用于打印火箭发动机热端及推进部件（喷注器 / 喷注头、歧管、燃烧室与涡轮泵组件）的激光粉末床熔融（LPBF / DMLS）及大幅面金属 3D 打印设备。依 2024 年 9 月的授权协议，SpaceX 在 Velo3D Sapphire 系统上打印 Raptor/Merlin 零件；EOS 与尼康 SLM Solutions 供应整个可复用火箭发动机行业（ArianeGroup、Rocket Lab、LEAP 71）使用的 DMLS/LPBF 设备。",
  "launch_engine_metal_am_powder_merchant": "用于增材制造及锻造火箭发动机零件的航空级金属粉末（镍 / 钴 / 钛基高温合金；再生冷却燃烧室内衬用铜合金）及特种合金原料。商用供应商包括 Carpenter Additive（卡彭特科技）与 ATI。SpaceX 的 GRCop 类铜内衬合金为 NASA 研发，且基本为自研 / 内部生产；商用粉末层供应更广义的发动机增材制造行业。",
  "org_moog": "美国精密运动控制供应商；设计并制造运载火箭推力矢量控制作动器（机电、电液、电静液）及低温推进剂 / 增压介质控制阀。其 TVC 作动器已在 ULA Vulcan 一级、Antares 一级、Centaur 与 Ares 上面级飞行验证——即除 SpaceX（其发动机作动为自研封闭）以外可复用 / 一次性发射型号的商用 TVC 层。",
  "org_woodward": "美国控制系统供应商（科罗拉多州 Fort Collins）。其 Space & Defense 业务供应运载火箭主发动机控制、推力矢量控制作动、飞控作动、控制阀与伺服阀，以及卫星单组元 / 冷气阀门与万向节作动——面向发射行业的商用作动 / 阀门层。",
  "org_parker_hannifin": "美国运动与控制巨头；Parker Aerospace 为导弹、火箭及运载火箭供应发动机燃油 / 润滑 / 热管理系统、液压、流体管理及航空阀门（如 NASA SLS 与 Orion；历史上的航天飞机与阿波罗推进剂供给阀）。面向发射的商用流体系统 / 阀门层。",
  "org_velo3d": "美国金属增材制造原始设备制造商（Sapphire 激光粉末床熔融系统，可打印免支撑的复杂金属零件）。SpaceX 使用 Velo3D Sapphire 打印机生产包括 Raptor 零件在内的发动机组件；2024 年 9 月 SpaceX 签署非独占授权协议（500 万美元技术许可 + 300 万美元工程 / 支持）。是唯一一家与 SpaceX 确认存在合作关系的发动机相关商用供应商。",
  "org_eos_gmbh": "德国金属 / 高分子增材制造原始设备制造商；工业 DMLS（直接金属激光烧结，一种激光粉末床熔融工艺）设备的领先供应商。EOS 系统为整个发射行业打印火箭发动机零件——例如将 ArianeGroup 一个喷注头由 247+ 个零件整合为一体，以及铜合金燃烧室（与 AMCM 合作）。私营（家族 / 创始人持有），故无股票代码。",
  "org_nikon_slm_solutions": "德国金属增材制造原始设备制造商（选区激光熔化 SLM，即 LPBF），自 2023 年 1 月起为尼康公司全资子公司。为可复用火箭发动机供应大幅面金属 3D 打印设备（SLM-500、NXG 级）——与 Rocket Lab 就超大平台签署谅解备忘录；为 LEAP 71 提供 IN718 材质的全流量分级燃烧（FFSC）喷注头；为带一体化冷却通道的高校可复用发动机项目供货。",
  "org_carpenter_additive": "Carpenter Technology Corporation 旗下业务部门，供应用于增材制造的高品质铁基、镍基、钴基与钛基航空合金金属粉末。粉末用于增材制造火箭发动机及推进部件（燃烧室换热器用铜合金；热端用镍 / 钴高温合金）。面向发动机增材制造行业的商用粉末层。",
  "org_ati": "美国特种材料生产商，生产用于增材制造（DMLS / EBM）的钛及钛合金、镍基与钴基高温合金以及金属粉末（钛、钛铝化物、镍 / 钴高温合金）。供应航空喷气与火箭发动机及机体材料；面向发动机零件的商用粉末 + 轧制品层。",
  "org_rbc_bearings": "美国精密轴承制造商。其 Transport Dynamics FibriloidCR 低温自润滑球面轴承 / 杆端经过测试并已在运载火箭与卫星应用中飞行验证（-320 °F 低温至 +450 °F）；Western Precision Aero 为火箭推力矢量功能供应齿轮箱 / 机电万向节组件。商用运载火箭轴承层。",
  "aerospace_aluminum_lithium_plate_sheet": "用于运载火箭贮箱筒段、箱底、级间段、级段适配器及推力结构的低密度、高刚度铝锂（Al-Li）轧制板材、薄板与型材。Falcon 9 的级段结构采用铝锂合金；铝锂是全行业供给可回收发射贮箱的商用材料层。合格的铝锂产能稀缺到原始设备制造商会签署长达十年的锁定协议。",
  "aerospace_titanium_mill_product": "用于再入控制面（栅格舵）、发动机硬件及高温结构的航空级钛材轧制品（板、棒、坯、锻造料）。熔炼 / 轧制层高度集中（VSMPO-AVISMA、ATI、TIMET），并在 2022 年因俄罗斯钛材敞口被记录为一条供应风险主线。",
  "titanium_sponge_feedstock": "海绵钛——熔炼所有航空轧制钛材的上游原料。一个近乎单一地理来源的环节：美国本土海绵钛生产已实质停止，使西方航空业近乎依赖进口，日本（大阪钛、东邦钛）为主要商用来源，外加北美的 PCC/TIMET。",
  "large_aerospace_titanium_forging_casting": "用于可回收发射再入控制面的大型单件钛铸件 / 锻件——Falcon 9 的高超声速栅格舵用单块钛材整体铸造，因此无需隔热即可承受再入热量并实现复用而无需每次飞行更换。钛铸 / 锻件层（Howmet、PCC）是公认的航空产能卡脖子环节。",
  "aerospace_investment_casting_forging": "供给火箭发动机及主结构的高端航空精密铸件与结构 / 旋转锻件。约 100 亿美元的板块，由近乎双寡头的两家供应商（Arconic/Howmet 与 Precision Castparts）主导，是发动机与机体生产长期且众所周知的产能卡脖子环节。",
  "org_constellium": "Constellium SE——领先的航空铝材生产商，并生产用于运载火箭贮箱与结构部件的专有 Airware 铝锂合金。已公开向蓝色起源 New Glenn 供应 Airware 铝锂板材 / 薄板；面向可回收发射贮箱的商用铝锂敞口。",
  "org_kaiser_aluminum": "Kaiser Aluminum Corporation——领先的半成品特种铝制品生产商，拥有重要的航空 / 高强度板材与薄板业务（华盛顿州 Trentwood 轧厂）。商用航空铝敞口；航空铝板的第二供应来源候选。",
  "org_arconic": "Arconic Corporation——主要的轧制铝及航空板材 / 薄板生产商，2016 年从美铝 Alcoa 分拆。历史上两大领先航空铸件 / 结构血统之一（另一家为 PCC）。2023 年被 Apollo Global Management 私有化。",
  "org_vsmpo_avisma": "VSMPO-AVISMA Corporation——全球最大的钛生产商，历史上是波音与空客的最大钛供应商。2022 年后西方航空钛材的出口管制 / 制裁环节；位于俄罗斯，国家集团 Rostec 持有约 25%+1 的股份。",
  "org_timet": "TIMET（Titanium Metals Corporation）——一体化钛生产商（海绵钛、铸锭、轧制品），据其母公司称为北美最大的海绵钛生产商与熔炼商。曾运营美国最后一座大型海绵钛工厂（内华达州 Henderson），自 2020 年起闲置。Precision Castparts（伯克希尔·哈撒韦）旗下子公司。",
  "org_toho_titanium": "东邦钛株式会社（Toho Titanium）——日本两家海绵钛生产商之一（另一家为大阪钛）。随着西方逐步摆脱对俄罗斯供应的依赖，日本海绵钛厂商共同成为西方可获取的航空海绵钛原料的主要商用来源。",
  "org_osaka_titanium": "大阪钛科技株式会社（Osaka Titanium）——仅次于 VSMPO-AVISMA 的全球第二大海绵钛生产商，也是日本两家海绵钛生产商之一。是西方可获取供应中航空海绵钛原料的核心商用来源。",
  "org_howmet_aerospace": "Howmet Aerospace Inc.——领先的高端工程航空部件供应商：精密铸件、锻件、钛轧制品 / 型材，并在航空紧固系统领域居全球第一。称其能够生产逾 90% 的全部航空发动机结构件与旋转件。两大主导航空铸 / 锻件生产商之一。",
  "org_precision_castparts": "Precision Castparts Corp.（PCC）——全球多元化复杂金属部件制造商：航空用锻件、精密铸件、紧固件与机体产品。两大主导航空精密铸件生产商之一，并通过 TIMET 成为北美最大的海绵钛生产商 / 熔炼商。伯克希尔·哈撒韦旗下公司。",
  "org_outokumpu": "Outokumpu Oyj——欧洲最大、美洲第二大的不锈钢生产商。公开报道为 SpaceX Starship 供应不锈钢；面向 Starship 主结构的商用 300 系不锈钢敞口。",
  "falcon9_strategic_radhard_processor_fpga": "发射 / 航天航电中高度集中、出口敏感的环节：面向最严苛 GEO / 深空辐射环境的真正抗辐射通用处理器、抗辐射 / 耐辐射 FPGA 与抗辐射存储器。这是卡脖子主线（可信代工厂极少、交付周期长），区别于 Falcon 9 等高节奏发射器在上升段航电上主要采用的 COTS 升级筛选路线。供应商集中于少数几家西方厂商（BAE RAD750/RAD5545、Frontgrade/Microchip、AMD/Xilinx，以及 DoD 资助的 SkyWater RH90 可信代工厂）。",
  "launch_cots_upscreened_avionics_silicon": "战略级抗辐射的商品化对照面：经过选型、辐射表征、验收测试，并以三模冗余、ECC、刷新与看门狗加以保护（而非支付完整抗辐射溢价）的商用现货芯片（如双核 x86）。这正是 SpaceX Falcon 级上升段航电以广泛商业供应实现辐射容限的方式，因此此处的芯片供应并非单一来源卡脖子。SpaceX 的航电设计本身为自研（must_build）；底层器件则是商品。",
  "launch_vehicle_space_imu_gnss": "向容错 GNC 回路及自主飞行安全位置解算供给数据的惯性测量 / 基准单元（环形激光陀螺、半球谐振陀螺、光纤陀螺、MEMS）以及 GNSS 接收机。高可靠航天级 IMU / 陀螺层集中于两家主导西方厂商（霍尼韦尔 MIMU、诺斯罗普·格鲁曼 SIRU/HRG），赛峰 Safran 与诺斯罗普-LITEF 的 MEMS 为更低成本的近邻方案；现代发射器也可掺用经升级筛选的战术级 MEMS 器件。",
  "launch_vehicle_star_tracker": "用于上面级、航天器以及（日益增多的）星座平台精确姿态确定的光学恒星基准敏感器。商用星敏感器市场由 Sodern（ArianeGroup）领跑，Jena-Optronik（空客）与 Ball/BAE 为其他成熟的高可靠供应商；新太空巨型星座需求带动了更高产率、更低成本的变体。相较于 Falcon 9 上升段，其对载荷 / 航天器姿态更为相关，但仍是更广义可回收发射 + 在轨链路的核心 GNC 敏感器。",
  "space_grade_connector_harness_launch": "运载火箭航电互连：可承受振动、热循环、出气与辐射的加固型圆形 / 矩形连接器、密封件及屏蔽线束。供应面广但质量集中于少数互连厂商（Glenair、TE/DEUTSCH、Amphenol）。区别于轨道数据中心连接器节点；这是可复用栈上的上升 / 回收线束。",
  "flight_termination_ordnance_safe_arm": "自主飞行安全系统的火工 / 军械部分：由星上 AFTS 计算机指令的保险解保装置、起爆器与销毁装药。飞行安全决策计算机为 SpaceX 自研（定制 AFTS），但合格的保险解保 / 火工硬件是一个高度集中的商用环节，由 Pacific Scientific Energetic Materials（PacSci EMC，Fortive 子公司）主导，它是大多数美国运载火箭所采用的保险解保 / 解保-点火装置的成熟美国供应商。",
  "org_bae_systems": "英国国防 / 航空主承包商，是战略抗辐射航天处理器的传统领导者（150nm 的 RAD750、45nm 的 RAD5545；12nm 抗辐射库研发中）。其单板计算机长期是高可靠航天计算的主力。BAE 还于 2024 年并入 Ball Aerospace，引入 CT-2020 抗辐射星敏感器。在伦敦证券交易所上市。",
  "org_frontgrade_technologies": "自称为航空、国防与医疗行业最大的模拟与抗辐射电子供应商；产品组合涵盖抗辐射 FPGA、存储器、微处理器、任务处理子系统、ASIC 及电源管理。前身为 Cobham Advanced Electronic Solutions（CAES）；由 Veritas Capital 持有，故为私营（无公开股票代码）。",
  "org_microchip_technology": "美国半导体厂商，两大主导航天级 FPGA 供应商之一。其 RTG4 耐辐射 FPGA 经设计加固以抵御 LEO/MEO/GEO/HEO / 深空的单粒子翻转，其 RT PolarFire FPGA 取得 QML Q 类航天资质。在纳斯达克上市（MCHP）。",
  "org_amd": "前 Xilinx 航天级 FPGA 产品线的拥有者，两大主导航天 FPGA 供应商中的另一家。航天级 XQR Kintex UltraScale（20nm，搭载火星 Perseverance 飞行）及较新的耐辐射 XQR Versal 自适应 SoC（B 类资质，2023 年初起出货，可在飞行中重编程）支撑高性能星上处理。在纳斯达克上市（AMD）。",
  "org_skywater_technology": "美国资本的纯晶圆代工厂，DMEA Cat-1A 可信代工厂；获 DoD 资助（最高 1.7 亿美元，2022 年 9 月再增 9900 万美元）以扩大战略抗辐射（RH90，90nm）电子的本土生产。代表战略抗辐射环节由政策驱动的本土产能建设。在纳斯达克上市（SKYT）。",
  "org_northrop_grumman": "美国航空 / 国防主承包商，凭借其可扩展航天惯性基准单元（SIRU）系列成为另一家主导的航天级惯性厂商，该系列基于半球谐振陀螺（HRG）技术，已在逾 200 颗航天器上累计 5000 万在轨小时而无一次任务失败，并因其石英结构天然抗辐射。其 LITEF 子公司供应 MEMS/FOG IMU。在纽交所上市（NOC）。",
  "org_sodern": "法国光电厂商，自称为星敏感器全球领导者，提供市场上最全面的产品系列（Hydra、Auriga 系列），拥有从 LEO 到深空的丰富飞行经历；Auriga 单元配装大型 LEO 通信星座。ArianeGroup（空客 / 赛峰私营合资企业）子公司，故无自身公开股票代码。",
  "org_jena_optronik": "德国星敏感器 / 姿轨控敏感器制造商，与 Sodern 并列为两家成熟的欧洲星敏感器厂商之一。其 ASTRO APS 被称为全球最成功、应用最广的高可靠卫星姿轨控敏感器；紧凑型抗辐射 ASTRO CL 面向小卫星与巨型星座。空客防务与航天（Airbus SE，泛欧巴黎 AIR.PA）子公司。",
  "org_glenair": "美国互连厂商，专注于小型化、重量敏感的航天连接器与线束。其 Series 80 Mighty Mouse 被指定用于全球数百项关键互连应用，以约一半的尺寸与重量成为原 MIL-DTL-38999 用户事实上的高性能连接器方案。Glenair 提供具备成熟飞行经历的完整运载火箭航电互连系统。私营。",
  "org_pacsci_emc": "美国军械 / 火工厂商，是航天运载火箭保险解保 / 解保-点火装置、起爆器及飞行终止火工品的成熟供应商，其硬件应用于大多数美国发射项目。Ralliant Corporation（纽交所：RAL）子公司。",
  "org_mercury_systems": "美国国防电子厂商，制造航天合格的 FPGA 处理板（包括首块采用 AMD Xilinx Versal 技术的航天合格处理板），将商用耐辐射芯片集成进飞行处理子系统。是板级集成商而非芯片厂商。在纳斯达克上市（MRCY）。",
  "aerospace_carbon_fiber_composite_material": "用于在可回收运载火箭上制造载荷整流罩及其他复合材料主结构的航空级 PAN 基碳纤维及基体树脂 / 预浸料。Falcon 9 的载荷整流罩为碳纤维-铝蜂窝夹层结构。整流罩制造在 SpaceX 大量自研（其自有 Hawthorne 热压罐）；商用敞口在于上游碳纤维 + 树脂材料层（Toray、Hexcel、Teijin、三菱化学、Syensqo）。高模量 / 高强度航空碳纤维处于既有出口管制体制之下（瓦森纳两用清单；美国 EAR/ITAR），对谁可供货、向谁供货构成结构性约束。",
  "launch_vehicle_copv_pressurant_vessel": "复合材料缠绕压力容器，用于储存高压氦气，以在发动机消耗推进剂时为运载火箭推进剂贮箱增压。行业标准结构为在薄金属（如铝）内衬上缠绕碳纤维复合材料；较新的 IV 型 / V 型设计采用聚合物内衬或无内衬碳纤维缠绕。在 Falcon 9 上 COPV 置于推进剂贮箱内部，且 SpaceX 自研制造自己的 COPV（自研封闭）。商用群体——Infinite Composites、Steelhead Composites、HyPerComp、General Dynamics-OTS——向更广义的发射 / 航天器行业供应 COPV，是非自研项目的可投资敞口；碳纤维缠绕本身又回溯至同一航空碳纤维材料层。",
  "org_toray": "日本化工 / 材料集团；全球最大碳纤维生产商（TORAYCA 品牌；拥有大丝束工业纤维品牌 Zoltek）。供应用于商用飞机主结构的航空级中 / 高模量碳纤维，作为材料层也用于运载火箭复合结构（整流罩）及 COPV 缠绕。在几乎所有碳纤维所需的上游 PAN 前驱体领域亦占主导。",
  "org_hexcel": "美国先进复合材料厂商（纽交所：HXL）；HexTow 碳纤维与 HexPly 预浸料是主要商用与军用飞机（A350 XWB、波音 787、JSF）的主结构材料。中模量纤维领导者，自有 PAN 前驱体。作为材料层供给运载火箭复合结构，并通过 HexTow IM 级纤维供给 COPV 缠绕（如与 HyPerComp 联合开发的 IV 型 COPV）。",
  "org_teijin": "日本材料集团（东京：3401）；Teijin Carbon 以 Tenax 品牌生产高性能碳纤维。Tenax 中模量纤维（如 IMS65）已取得航空结构用资质（与 Syensqo 树脂的 NCAMP 资质；并由 Collins Aerospace 单独取得资质）。供给运载火箭复合结构的商用航空碳纤维材料层的一部分。",
  "org_mitsubishi_chemical": "日本化工集团（东京：4188）；生产 Pyrofil PAN 碳纤维及 Newport 复合材料，用于飞机系统与结构件以及导弹、火箭与卫星。拥有 Pyrofil 中模量航空牌号，并在 2025-2027 年间于东海（日本）与萨克拉门托（美国）将碳纤维产能翻倍，以供包括航空在内的高端应用。商用航空碳纤维材料层的一部分。",
  "org_syensqo": "特种材料公司（泛欧布鲁塞尔：SYENS），2023 年 12 月自索尔维 Solvay 拆分；持有原索尔维 / Cytec 复合材料业务。供应航空合格的环氧树脂体系与预浸料（如 Prism EP2400，与 Teijin Tenax 纤维取得 NCAMP 资质）及用于航空结构的碳纤维。代表供给运载火箭复合结构的商用碳复合材料层中的树脂 / 预浸料（基体）部分。",
  "org_infinite_composites": "美国（俄克拉荷马州 Tulsa）厂商，为运载火箭、卫星、月球着陆器及太空加注站的增压与推进剂贮箱制造无内衬（V 型）复合压力容器与 COPV。私营公司；展示的政府 / 研究客户包括 NASA、美国空军、美国陆军。代表非自研发射项目可采购的商用 COPV 群体（SpaceX 自身自研 COPV）。",
  "org_steelhead_composites": "美国（科罗拉多州 Golden）厂商，制造集成于运载火箭推进系统的高性能 COPV，并用作航天器推进的主 / 辅贮箱，其内衬按与自燃、低温或加压气体推进剂的相容性选定。私营公司；面向更广义发射 / 航天行业的商用 COPV 群体的一部分。",
  "org_hypercomp_engineering": "美国（犹他州 Brigham City）复合材料缠绕压力容器（COPV）的开发、合格鉴定与生产商；通过 AS9100-D 认证，产品应用包括航天运载火箭等。与 Hexcel 联合开发了采用 HexTow IM11-R/12K 碳纤维、面向航空与航天的 IV 型碳纤维缠绕 COPV。私营公司；商用 COPV 群体的一部分。",
  "org_gd_ots": "通用动力（纽交所：GD）旗下复合结构部门（Lincoln Operations）。是 NASA SLS 芯级与上面级 COPV 以及多颗为推进子系统提供压缩气体的卫星 COPV 的设计授权方；应用还包括运载火箭与卫星推进。通过母公司通用动力上市。商用 COPV 群体的一部分（SLS、卫星——而非自研封闭的 SpaceX）。",
  "helium_pressurant_supply": "用于为地面与飞行流体系统增压、吹除推进剂管路并为可回收发射运行提供低温冷却的商用液 / 气态氦。它是推进剂线路中供应最集中的输入：氦是少数几个天然气田的副产品，生产商寥寥，且周期性短缺，因此发射运营方必须锁定专用供应（如 NASA 与空气化工产品就 KSC / 卡纳维拉尔角的液氦单一来源合同）。",
  "liquid_oxygen_lox_supply": "用作煤油 / 液氧（Falcon 9 / Merlin）与甲烷 / 液氧（Starship / Raptor）两类可回收发射推进剂系统氧化剂的商用液氧。液氧由低温空分制取；商用供应是工业气体巨头的寡头格局。对于高节奏可回收发射，约束在于设于发射场附近的专用空分产能与低温槽车交付，这正是 Linde 在 Brownsville（Starbase）与佛罗里达 Mims（卡纳维拉尔角周边发射）建设 / 运营专用空分装置的原因。",
  "liquid_methane_lch4_supply": "用作甲烷 / 液氧 Starship/Super Heavy 可回收系统燃料的火箭级液态甲烷（LCH4）。与液氧和氦不同，甲烷并非空分产物：SpaceX 采购液化天然气（LNG，主要成分为甲烷）并提纯 / 调质至火箭级，依托天然气 / LNG 商用网络（Brownsville 附近的 LNG 接收站）而非工业气体巨头。这是一条独立的供应链（低温天然气液化与运输），相对集中度较低，但火箭级纯度与低温槽车物流仍制约节奏。",
  "org_air_products": "美国总部（宾州 Allentown）工业气体巨头；全球五大工业气体生产商之一，也是航天发射行业的领先氦供应商。获得 NASA 的液氦单一来源供应合同（3300 万升，约 10.7 亿美元），用于肯尼迪航天中心 / 卡纳维拉尔角发射运行，并包含其专有液氦泵。",
  "org_nippon_sanso_holdings": "日本总部工业气体巨头（前身大阳日酸 Taiyo Nippon Sanso）；全球第四 / 第五大工业气体集团，由三菱化学集团控股。其美国运营公司为 Matheson Tri-Gas（德州 Irving）。自称为全球仅有的少数氦生产与供应商之一，拥有自有氦源权益及长期供应合同。",
  "org_messer": "德国家族所有的工业气体集团；自称为全球最大的私营工业气体公司，也是横跨美洲、亚洲与欧洲的领先工业 / 医用气体公司。2024 年 6 月完成从 BLM 收购美国联邦氦系统（Cliffside 气田、储备及 423 英里粗氦管道），增强其本土氦地位。长期少数股东为 GIC。",
  "starship_pica_class_ablator": "酚醛浸渍碳烧蚀材料（PICA）类低密度烧蚀热防护材料——返回舱与再入系统传统可复用 / 再入飞行器隔热罩的基础。由碳 FiberForm 预制体（以人造丝 / 莱赛尔碳前驱体制成）浸渍酚醛树脂构成。区别于 Starship 的可复用二氧化硅陶瓷瓦，但同一供应层（碳前驱体 → 预制体）是美国可回收发射 / 再入飞行器基础已记录的热防护卡脖子环节。",
  "pica_rayon_lyocell_carbon_precursor": "纤维素碳前驱体纤维（非织造人造丝，现为本土莱赛尔），在 PICA 类烧蚀材料内部碳化为 FiberForm 预制体。这是已记录的单一 / 近单一来源环节：传统 NASA 合格鉴定的人造丝供应商（西班牙 SNIACE）停产，迫使反复重新鉴定并由 NASA 推动转向本土莱赛尔前驱体（PICA-D）。烧蚀热防护链中最难寻找第二来源的单项。",
  "pica_carbon_fiberform_preform": "低密度碳纤维 FiberForm 预制体——刚性碳化纤维素纤维基体，一经酚醛浸渍即成为 PICA 类烧蚀材料。由 Fiber Materials Inc（FMI，缅因州 Biddeford）制造；NASA Ames 与 FMI 合作升级设施，以莱赛尔前驱体制造航空级 FiberForm（PICA-D）。供给再入飞行器隔热罩的近单一来源航空预制体层。",
  "reusable_launch_ceramic_silica_tile": "刚性高纯二氧化硅 / 陶瓷可复用表面隔热瓦（航天飞机传统 LI-900/LI-2200 级；Starship 六边形二氧化硅陶瓷瓦）。烧蚀型 PICA 的可复用对应物：意在无需更换即可反复再入。对 Starship 而言这种瓦为 SpaceX 自研封闭——在 SpaceX 自有的瓦“烘焙厂”（Roberts Road）内部生产，而非向商用瓦厂商采购——故此处真正的商用敞口薄弱。传统行业瓦厂商为 Lockheed Missiles & Space（LI-900）。",
  "reusable_launch_tps_tile_adhesive_sip": "高温室温硫化（RTV）硅胶瓦粘接剂，以及将刚性热防护瓦与飞行器结构变形解耦的 Nomex 毡应变隔离垫（SIP）。航天飞机传统组合：RTV-560 硅胶将瓦粘接到 Nomex 毡 SIP，后者再粘接到机体。商用材料存在（硅胶 RTV；芳纶毡），但 Starship 特定的瓦附着方法由 SpaceX 自定义，并未公开外采于这些供应商。",
  "org_lenzing": "奥地利纤维素纤维生产商；LENZING / TENCEL 莱赛尔的制造商。其莱赛尔纤维是 NASA PICA-D 烧蚀隔热罩的本土替代碳前驱体（碱金属含量低使其适合作碳纤维前驱体）。本属单一来源的 PICA 前驱体环节中可公开投资的一面。",
  "org_fiber_materials_inc": "缅因州 Biddeford 的高温碳 / 碳与增强复合材料厂商；生产 PICA 类烧蚀材料所用的低密度碳 FiberForm 预制体，以及再入鼻锥与火箭发动机喉衬 / 喷管。NASA Ames 与 FMI 合作以莱赛尔前驱体制造航空级 FiberForm（PICA-D）。近单一来源的航空预制体供应商。",
  "org_lockheed_martin": "美国航空 / 国防主承包商；Lockheed Missiles & Space Company（加州 Sunnyvale）研制并生产了航天飞机的 LI-900 / LI-2200 可复用二氧化硅表面隔热瓦（99.9% 纯二氧化硅玻璃纤维）。可复用陶瓷热防护瓦的传统商用厂商——可复用瓦层的行业参照点（Starship 自身的瓦为自研封闭）。",
  "org_momentive_performance_materials": "全球高性能硅胶厂商；为航空热防护系统供应 RTV 硅胶（原位浇注隔热、隔热毯粘接）。历史上用于将航天飞机热防护瓦粘接到应变隔离垫的 RTV-560 级红色苯基甲基硅胶的制造商。瓦粘接工艺的行业 RTV 粘接剂层。",
  "org_sniace": "西班牙特种纤维素与粘胶 / 人造丝生产商（Torrelavega）。曾是 NASA 合格鉴定的 PICA 碳前驱体非本土人造丝供应商；其人造丝被碳化为 PICA 隔热罩用 FiberForm。已停止人造丝 / 粘胶生产并进入清算，切断了传统 PICA 前驱体供应链，并触发 NASA 转向莱赛尔（PICA-D）替代。",
  "spacex_reusable_launch_stack": "以 SpaceX 为核心的可回收轨道发射能力图谱。Falcon 9 与 Starship/Super Heavy 作为产品分支分开呈现；Dragon、Starlink 服务、Falcon Heavy 及载荷客户产品被有意排除在产品边界之外。",
  "spacex_reusable_orbital_launch_capability": "需求侧能力：以可回收发射硬件将载荷质量送入轨道，实现高节奏、受控回收与有界翻修成本。",
  "falcon9_reusable_launch_branch": "以一级回收、Merlin 复用、容错航电、整流罩回收及飞后翻修为核心的在役 Falcon 9 复用路线。其商业上已成熟，但可投资的约束在于检查、验收测试、靶场可用性及任务推进剂储备在多大程度上仍制约节奏与边际成本。",
  "starship_superheavy_reusable_branch": "面向完全可复用 Starship 上面级与可复用 Super Heavy 助推器的开发路线，载荷能力大得多，但快速复用、隔热罩、塔臂捕获与许可等约束尚未解决。",
  "reusable_launch_common_enablers": "SpaceX 各飞行器共用的复用层：健康监测、发动机寿命裕度、飞行安全、推进剂运行、验收测试与回收运行。",
  "spacex_launch_ground_stack": "面向高节奏可回收发射的地面基础设施与流程层：塔架系统、推进剂加注、发射台周转、静态点火验收与靶场协调。",
  "falcon9_booster_reuse_stack": "一级分支，涵盖助推器推进、结构、再入控制、着陆硬件、回收运行与翻修。其重要性在于每次复飞都必须通过回收级段检查与验收信心，节奏才能转化为更低的边际发射成本。",
  "falcon9_merlin_engine_cluster": "九台 Merlin 一级推进集群；复用经济性取决于发动机寿命裕度、检查时间与验收测试合格率。",
  "merlin_1d_reuse_qualification": "针对发动机检查、趋势数据、热试车裕度及回收后飞行就绪的复用验收逻辑。它是瓶颈，因为保守的发动机筛查虽保护可靠性，却可能迫使额外测试时间、更换零件或在市场看到复用真实边际成本之前提前退役助推器。",
  "falcon9_engine_turbopump_reuse_inspection": "回收后对涡轮机械的检查与趋势筛查。之所以难以快速通过，是因为涡轮泵寿命受高速旋转硬件、热循环与异常历史驱动，而公开细节稀少到足以使该分支必须保持为研究前沿。",
  "falcon9_engine_chamber_nozzle_life_margin": "针对反复点火、上升载荷、再入点火与着陆点火的发动机热与结构寿命裕度模型。约束并非发动机能否飞一次，而是 SpaceX 能多有把握地延长复用寿命而不引发昂贵检查或提前退役。",
  "falcon9_aluminum_lithium_tank_structure": "可复用级段结构与贮箱系统；反复载荷与着陆环境使结构检查与疲劳裕度变得相关。",
  "falcon9_stage_structural_fatigue_life": "对回收级段在上升、再入、着陆、运输与复飞各循环中的疲劳跟踪。它制约复用深度，因为运营方必须在不把每次回收都变成缓慢拆解工程的前提下证明结构裕度。",
  "falcon9_grid_fin_reentry_control": "可展开栅格舵，用于在大气再入过程中引导返回助推器飞向着陆区或海上平台。",
  "falcon9_landing_legs": "用于垂直回收的可展开一级着陆腿；虽是成熟子系统，但仍是回收可靠性链的一部分。",
  "falcon9_boostback_entry_landing_burns": "各回收点火段的制导与推进剂分配；直接决定回收成功率与载荷性能权衡。",
  "falcon9_landing_propellant_margin": "在载荷投送与用于返推、再入、着陆点火的储备推进剂之间的任务设计权衡。它是产能 / 经济性瓶颈，因为更高的回收储备虽能保护硬件，却可能降低载荷裕度或迫使采用海上平台剖面。",
  "falcon9_droneship_rtls_recovery_ops": "自主海上港口平台或回场着陆回收、安全处置、运输与复用交接的运行流程。当海况、船只可用性、港口物流或着陆场可用性中断回收-翻修链时，它会制约发射节奏。",
  "falcon9_postflight_inspection_refurb": "助推器回收后的周转流程；瓶颈在于复飞前的时间、检查信心、更换范围与验收测试。这是最直接的 Falcon 9 复用约束，因为它将回收硬件转化为可售发射运力。",
  "falcon9_second_stage_payload_delivery": "一次性上面级投送层。它本身并非可复用硬件，但影响 Falcon 9 任务包络与发射经济性。",
  "merlin_vacuum_upper_stage_engine": "Falcon 上面级上的单台 Merlin Vacuum 发动机；载荷指南说明了其固定喷管与上面级作用。",
  "falcon9_fault_tolerant_avionics_gnc": "容错航电与制导、导航、控制层，依据载荷指南具备单故障容限及冗余 / 三余度元件。其商业上已成熟，但复用仍取决于飞行软件信心、传感器冗余、异常审查与回收制导可靠性。",
  "falcon9_pneumatic_stage_separation": "Falcon 载荷指南中记载的低冲击分离子系统；其重要性在于分离可靠性影响任务与复用安全。",
  "falcon9_fairing_recovery_reuse": "载荷整流罩回收与复用分支；具经济相关性，但独立于一级复用。",
  "starship_superheavy_vehicle_stack": "Starship 路线的助推器与船体一体化架构。它制约商业化，因为完全复用需要助推器、船体、隔热罩、推进剂运行、塔臂接口与许可节奏作为一个可重复系统协同工作，而非孤立的测试成功。",
  "superheavy_reusable_booster": "Starship/Super Heavy 的可复用一级助推器分支，包括 Raptor 集群、返推、栅格舵与捕获接口。它受发动机集群可靠性、回场制导、塔臂捕获裕度与地面场区可用率制约，因此仅有回收成功不足以支撑高节奏商业复用。",
  "starship_raptor_engine_cluster_33": "Super Heavy 的大规模集群甲烷 / 液氧推进层；在可靠性、节流与复用方面是关键的集成瓶颈。",
  "raptor_methalox_full_flow_engine": "用于 Starship 与 Super Heavy 的可复用甲烷 / 氧发动机系列；发动机可靠性与复用裕度是该路线的核心。",
  "raptor_clean_reuse_margin": "反复发射、着陆与复飞循环所需的发动机健康与燃烧稳定裕度。",
  "subcooled_methane_oxygen_propellant_ops": "针对过冷液态甲烷与氧的地面加注、致密化、蒸发控制与发动机供给运行。",
  "superheavy_grid_fin_control": "面向 Super Heavy 返回与捕获剖面的栅格舵与控制面层。",
  "superheavy_tower_catch_landing_interface": "发射塔捕获接口。这是一个高杠杆的 Starship 复用瓶颈，因为它以特定场区基础设施、精确进近逻辑、场区可用性与捕获后检查能力取代了着陆腿。",
  "superheavy_rtls_boostback_profile": "Super Heavy 回收的回场任务设计与控制方法。它制约 Starship 节奏，因为推进剂储备、着陆精度、中止包络与塔架可用性必须在不牺牲载荷经济性的前提下相互对齐。",
  "starship_ship_reusable_upper_stage": "面向轨道投送与返回的可复用上面级 / 航天器分支。它是路线中最难的环节，因为轨道再入、隔热罩耐久性、襟翼控制、发动机再点火、载荷舱运行与飞后检查都必须收敛为可重复的复用。",
  "starship_engine_mix_sea_level_vacuum": "依据 2026 年文件描述，船体推进采用海平面与真空优化 Raptor 发动机的组合。",
  "starship_heat_shield_tile_system": "面向船体再入的可复用热防护层；瓦的耐久性、附着、检查与更换时间是核心瓶颈。它直接决定 Starship 复用看起来像航空式快速周转，还是像缓慢的翻修工程。",
  "starship_heat_shield_tile_bonding_process": "在上升振动、加热与再入循环后进行的瓦附着、缝隙控制、检查、更换与复飞验收流程。这是瓶颈，因为快速的 Starship 复用取决于发现受损瓦、恢复粘接与缝隙完整性，并在不把每次回收都变成缓慢热防护翻修工程的前提下放行船体再次飞行。",
  "starship_stainless_steel_primary_structure": "针对 Starship 级热与制造权衡选定的不锈钢结构；确切的合金 / 工艺细节仍在本轮范围之外。",
  "starship_flap_reentry_control": "面向大气再入、姿态控制与着陆转换的船体襟翼与控制方法。",
  "starship_payload_deployment_bay": "面向高质量 Starship 任务的载荷容纳与部署分支。",
  "starship_reentry_landing_burn_profile": "面向船体再入、翻转、发动机再点火与末端着陆点火的飞控方法。它制约复用，因为再入控制、热裕度、再点火可靠性、着陆精度与飞后状态共同决定船体能否以商业节奏复飞。",
  "integrated_launch_tower_chopsticks": "面向 Starship/Super Heavy 的发射、堆叠与捕获基础设施；使复用依赖于地面场区精度与可用率。",
  "methane_oxygen_ground_propellant_system": "面向高节奏甲烷 / 液氧发射的储存、加注、预冷与贮罐区运行。",
  "launch_pad_rapid_turnaround_process": "两次发射之间的发射台检查、修复、推进剂复位、靶场就绪与飞行器总装流程。",
  "vehicle_health_monitoring_telemetry": "用于判定回收硬件能否再次飞行的飞行与地面遥测流水线。",
  "reuse_acceptance_static_fire_test_process": "总装或翻修后的测试与验收流程，包括必要时的静态点火逻辑。",
  "autonomous_flight_safety_system": "在发射与回收运行期间界定公共安全风险的飞行安全系统层。",
  "range_safety_airspace_coordination": "面向高节奏运行的危险区域、发射窗口、NOTAM、靶场资产与回收区协调。",
  "cryo_ground_loading_sequence": "面向低温发射运行的时序、预冷、推进剂调质、保持逻辑与中止恢复。",
  "methalox_engine_test_stands": "面向 Raptor 鉴定、验收、异常复现与复用裕度学习的地面测试基础设施。",
  "faa_launch_reentry_license_cadence": "对 SpaceX 发射与再入活动的监管节奏约束。对于 Starship/Super Heavy 的 Boca Chica，FAA 页面提及拟批准每年最多 25 次轨道发射与着陆的授权。",
  "reusable_launch_cost_per_kg_metric": "面向投资者的指标，衡量复用是否转化为载荷质量经济性，而不只是回收的视觉效果。当前图谱将其保持为阻断性未知，直到发射价格、载荷质量、复用深度、翻修与回收成本能与经审核的来源挂钩。",
  "booster_reflight_count_metric": "观测到的助推器复用深度；SpaceX 2026 年文件措辞是高重复使用的证据，但在能够支撑成本论断之前仍需独立运行审计。",
  "launch_cadence_metric": "将飞行器复用、发射台周转、监管批准与需求积压联系起来的节奏指标。它只有在按场区与飞行器路线拆分时才有用，因为 FAA / 场区授权、地面运行、回收资产与客户需求可能各自独立制约。",
  "org_spacex": "Space Exploration Technologies Corp. 是两张以 SpaceX 为核心图谱中的产品拥有者 / 运营方。拥有者身份作为路线背景可见；本轮的公开文件来源仅作为上市背景研究输入，且在人工审核确认之前不推介任何在役股票代码或公开上市。",
  "org_rocket_lab": "具备发射与航天系统敞口的上市航天公司。作为可比 / 供应商能力敞口纳入，而非确认的 SpaceX 供应商。",
  "spacex_launch_customer_exposure_research": "面向未来对依赖 SpaceX 发射服务的上市公司进行需求侧分析的占位项。在存在专门的客户 / 需求关系之前，有意不将其作为供应商敞口连接。",
  "humanoid_robot_key_component_stack": "面向早期车队部署的商用人形机器人平台部件栈：执行器、手、电池与供电、热管理、传感、机载计算、控制软件、结构、安全、制造与服务。这是付费域候选图谱，而非经审核的投资产品。",
  "humanoid_workforce_automation_capability": "需求侧能力：机器人能够使用以人为中心的空间、工具与任务流程，而无需重新设计每个工作场所。",
  "humanoid_actuation_system": "关节模组、减速器、电机、轴承、编码器与驱动电子。它制约负载、行走稳定性、工况周期、噪声与使用寿命。",
  "humanoid_dexterous_hand_tactile_system": "手部机构、手指驱动、触觉阵列、滑移检测与本地手部控制。它决定机器人能否完成有用的操作，而不仅是行走演示。",
  "humanoid_battery_power_charging_system": "电芯选型、电池包架构、BMS、配电、对接与认证。它制约续航、车队可用率、滥用容限与可部署性。",
  "humanoid_thermal_management_system": "电机、驱动、电池与边缘计算的散热路径。糟糕的热设计会缩短有效工况周期，把演示变成短促爆发。",
  "humanoid_perception_sensing_stack": "相机、深度、激光雷达、IMU、编码器、力 / 力矩、触觉、接近与音频传感。传感器对齐与漂移会在整机层面变成控制误差。",
  "humanoid_onboard_compute_control_electronics": "边缘 AI 计算、实时控制器、电机控制网络、电源隔离与安全电子。它必须把自主性塞进紧张的功率与散热包络。",
  "humanoid_structure_materials_harness": "骨架、壳体、外皮、布线、连接器、足部与可维护模块。重量、刚度、线缆疲劳与装配公差决定真实的车队可靠性。",
  "humanoid_locomotion_control_software": "全身控制、平衡、步态、状态估计、接触控制、跌倒恢复与运行时安全监控。",
  "humanoid_manipulation_ai_data_stack": "视觉-语言-动作策略、抓取规划、遥操作数据、模仿 / 强化学习训练、任务规划与车队学习。",
  "humanoid_manufacturing_test_safety_service": "总装、标定、老化、可追溯性、功能安全、急停、工况周期验证、现场服务与备件闭环。",
  "humanoid_rotary_joint_module": "用于肩、髋、腕、踝的高扭矩密度旋转关节。它制约有效负载，因为电机、减速器、轴承、编码器、驱动、散热路径与线束都必须装进一个可维护关节内。",
  "humanoid_linear_joint_module": "用于腿、膝、躯干或高载荷轴的大力直线执行器路径。之所以难以通过，是因为丝杠寿命、冲击载荷、润滑、密封与紧凑封装都影响现场可靠性。",
  "humanoid_reducer_transmission_stack": "决定回差、刚度、扭矩密度与寿命的谐波、行星、摆线或丝杠传动选择。瓶颈不仅是精度；而是可重复的关节级质量、全寿命验证以及足够多能满足人形规模执行器产量的合格供应商。",
  "humanoid_motor_stack": "为紧凑扭矩与散热而选型的无框 BLDC、直驱或准直驱电机。电机选择制约噪声、工况周期、效率、磁体敞口与执行器散热余量。",
  "humanoid_motor_drive_power_electronics": "面向众多分布式关节的栅极驱动、电流采样、逆变功率级、保护、EMI 滤波与控制回路。",
  "humanoid_joint_sensing_feedback": "用于闭环力与位置控制的绝对编码器、扭矩采样、电流采样、温度采样与标定模型。",
  "humanoid_joint_bearing_sealing": "紧凑关节内的薄壁轴承、交叉滚子轴承、密封、润滑与冲击处理。它制约车队可靠性，因为冲击、粉尘、线缆运动与维护可达性会把商品轴承变成关节专属的合格鉴定工作。",
  "humanoid_strain_wave_reducer": "紧凑高减速比方案，回差低，但在人形产量下面临寿命与成本压力。",
  "humanoid_planetary_roller_screw": "大力直线转换部件，其亚 3 微米精度的螺纹磨削与疲劳寿命可能成为高载荷执行器的瓶颈。",
  "humanoid_frameless_bldc_motor": "集成进关节壳体的紧凑型永磁电机。",
  "humanoid_rare_earth_magnet_supply": "影响紧凑电机及地缘政治供应风险的钕铁硼（NdFeB）类磁体供应。",
  "humanoid_inverter_power_stage": "为紧凑多轴关节电流控制选型的 MOSFET/GaN 功率级。",
  "humanoid_current_sense_gate_driver": "稳定扭矩控制与保护所需的高带宽电流采样与栅极驱动电子。",
  "humanoid_emi_filtering_grounding": "在密集布线与传感器间分布的电机驱动 EMI 控制。",
  "humanoid_five_finger_hand_mechanism": "用于物体抓取、工具使用与类人工作空间兼容的多自由度手部机构。它制约实用性，因为手指封装、驱动、触觉布线、损坏与更换成本决定操作能否在演示之外存活。",
  "humanoid_tendon_cable_transmission": "节省手指体积的远程驱动手部传动，但带来布线、拉伸、摩擦与标定问题。",
  "humanoid_micro_hand_actuator": "封装在手与腕体积内的小型电机、齿轮箱、丝杠或腱绳驱动。",
  "humanoid_fingertip_tactile_array": "指尖处用于滑移检测与抓取控制的密集压力 / 剪切传感。",
  "humanoid_palm_force_tactile_array": "用于稳定大物体操作与安全人机交互的掌部接触传感。",
  "humanoid_slip_detection_policy": "在物体掉落前将触觉数据流转化为握力调整的控制方法。",
  "humanoid_lithium_ion_cell_selection": "在能量密度、放电功率、安全与循环寿命之间权衡的电芯化学与形制选择。",
  "humanoid_battery_pack_enclosure": "面向运动机器人本体的机械电池包、互连、熔断、接触器、密封与滥用保护。它制约续航与安全，因为电池包封装必须吸收跌落、热事件、大电流瞬态与快速维护换装。",
  "humanoid_battery_management_system": "电芯监控、均衡、状态估计、保护、诊断与认证接口。",
  "humanoid_power_distribution_bus": "在电池包、计算与关节之间的分布式大电流配电、变换、保护与隔离。",
  "humanoid_charging_docking_interface": "车队充电坞、接触对齐、换电或充电控制与维护人机工学。它制约可用率，因为无法自主对接、安全充电并返回工作的机器人会造成隐性运营人力。",
  "humanoid_pack_safety_certification": "面向移动机器人电池的 UN38.3、UL 级、运输、滥用与功能安全要求。",
  "humanoid_motor_joint_thermal_path": "将绕组、驱动、齿轮箱与轴承栈的热量传导至壳体，而不造成可触温度或可靠性问题。",
  "humanoid_battery_thermal_safety": "电芯温度监控、散热、热失控抑制与电池包级断电。",
  "humanoid_compute_heat_spreader": "躯干 / 头部体积内边缘 AI 模组的热界面、均热板与散热路径。",
  "humanoid_airflow_liquid_cooling_loop": "受噪声、粉尘、冲击与维护约束的风扇、风道、热管、冷板或液冷回路设计。它制约持续作业，因为电机、驱动、电池与边缘计算会在密闭运动本体内产生热量。",
  "humanoid_thermal_sensor_map": "分布于电池包、电机、驱动、计算与壳体热点的热敏电阻与 IC 温度传感器。",
  "humanoid_sustained_duty_cycle_validation": "证明机器人能完成有效工班（而非仅短促演示）的热与可靠性测试流程。",
  "humanoid_stereo_rgb_camera": "用于感知、遥操作与场景理解的头部或躯干相机。",
  "humanoid_depth_camera_lidar": "用于导航、避障与操作工作空间估计的深度传感。",
  "humanoid_imu_attitude_sensing": "用于平衡、状态估计、冲击检测与跌倒恢复的惯性传感。",
  "humanoid_joint_encoder_position": "稳定本体控制与标定所需的绝对或增量关节反馈。",
  "humanoid_force_torque_sensing": "用于接触感知运动与操作的足部、腕部与关节力传感。",
  "humanoid_proximity_touch_safety": "面向人机交互与碰撞缓解的近距检测与接触传感。",
  "humanoid_audio_microphone_array": "面向以人为中心部署的语音、指令与态势感知传感。",
  "humanoid_edge_ai_compute_module": "在功率与散热限制内运行感知、策略推理与本地规划的机载 AI 加速器或 SoC。",
  "humanoid_realtime_mcu_safety_controller": "面向电机回路、急停、安全扭矩关断与健康监测的确定性控制器路径。",
  "humanoid_motor_control_network": "从中央控制器到众多分布式电机驱动器与传感器板的确定性通信。",
  "humanoid_time_sync_sensor_fusion": "对相机、IMU、编码器、力与触觉数据流的时间戳、同步、标定与融合。",
  "humanoid_safety_power_isolation": "将电池、大电流关节、计算与安全逻辑分隔开的电源隔离与保护架构。",
  "humanoid_lightweight_skeleton_frame": "在重量、刚度、冲击与可制造性间取得平衡的铝、镁、钢、聚合物或复合材料结构。",
  "humanoid_torso_enclosure_skin": "封装计算、供电、传感器、风扇并保障安全人体接触的外部防护表面。",
  "humanoid_wiring_harness_connectors": "穿过运动肢体的高挠曲线束、连接器、应力释放与维护布线。它制约可靠性，因为每个关节都增加弯曲循环、EMI、连接器保持与维护布线失效模式。",
  "humanoid_high_stiffness_low_mass_materials": "用于肢体与躯干、需在重量、刚度、疲劳、成本与可制造性间博弈的材料组合。",
  "humanoid_foot_contact_structure": "面向行走与平衡的足底、柔顺性、力传感、纹路与可更换设计。",
  "humanoid_serviceable_modular_design": "让车队运营方无需重建机器人即可更换关节、手、电池包、传感器与肢体的架构。",
  "humanoid_whole_body_control_stack": "对肢体、躯干、手、接触与质心的协调控制。",
  "humanoid_gait_balance_policy": "行走、站立、迈步、推扰恢复与不平地面策略。",
  "humanoid_sim_to_real_training_pipeline": "物理仿真、域随机化、策略迁移与硬件验证回路。",
  "humanoid_contact_force_control": "面向安全抓取、推动、倚靠与足-地交互的力-位置控制。",
  "humanoid_fall_recovery_safe_stop": "面向跌倒或失稳状态的检测、受控停止、恢复与维护交接。",
  "humanoid_runtime_safety_monitor": "面向扭矩、温度、电池、感知与人体接近约束的独立健康与安全监控器。",
  "humanoid_vla_policy_model": "将指令与感知映射为动作序列的具身 AI 模型。",
  "humanoid_grasp_planning_policy": "面向手部接近、抓取选择、握力调整与松开的规划与控制。",
  "humanoid_teleoperation_data_collection": "用于训练操作与任务策略的人类演示采集。",
  "humanoid_imitation_rl_training_loop": "将演示、奖励、仿真与车队失败转化为策略的训练回路。",
  "humanoid_task_planning_execution": "将用户目标分解为感知、运动、抓取、工具与验证步骤。",
  "humanoid_manipulation_benchmark_eval": "用于评判有用操作的任务套件、指标、数据回放与失败分类。",
  "humanoid_high_volume_joint_assembly": "以可重复质量装配电机、减速器、轴承、传感器、驱动、线束与壳体。",
  "humanoid_end_of_line_calibration_rig": "面向关节归零、扭矩标定、传感器对齐、电池检查与整机验证的工厂系统。",
  "humanoid_battery_pack_eol_test": "机器人集成前对电池包进行电气、热、均衡、安全、泄漏与充放电验证。",
  "humanoid_whole_robot_burn_in": "面向热浸、运动循环、传感器漂移与早期失效的工厂老化流程。",
  "humanoid_reliability_mtbf_tracking": "面向关节、手、电池、热与传感器失效的车队遥测与根因闭环。",
  "humanoid_functional_safety_estop": "面向停止状态、安全扭矩关断、电源隔离、人体接近与事件记录的安全架构。",
  "humanoid_field_service_spares_loop": "面向更换关节、手、电池、传感器、标定与翻修的服务流程。它制约总拥有成本，因为如果失效需要返厂或人工重新标定，试点车队就会变得昂贵。",
  "org_humanoid_harmonic_drive_systems": "日本上市的精密谐波齿轮敞口供应商候选；股票代码 6324.T 为东京上市敞口，而非美国主上市。图谱连接为部件敞口，而非确认的人形 BOM。",
  "org_humanoid_nabtesco": "日本上市的精密减速器供应商候选；图谱连接为减速器敞口，而非确认的人形 BOM。",
  "org_humanoid_leaderdrive": "中国上市的谐波减速器与旋转执行器供应商候选，对应人形减速器敞口；股票代码 688017.SS 为上海上市敞口，而非美国主上市。",
  "org_yaskawa_electric": "东京上市的伺服与运动控制供应商候选；股票代码 6506.T 为日本上市敞口，而非美国主上市。",
  "org_nidec": "东京上市的电机供应商候选；股票代码 6594.T 为日本上市敞口，而非美国主上市。",
  "org_humanoid_nvidia": "美国上市的机器人计算与物理 AI 平台供应商候选。",
  "org_humanoid_texas_instruments": "美国上市的模拟、BMS、电流采样与电机控制半导体供应商候选。",
  "org_humanoid_stmicroelectronics": "纽交所上市的 MCU、电机控制、传感与安全电子供应商候选。",
  "org_humanoid_tdk": "日本上市的传感器、无源元件、磁性与热管理元件供应商候选。",
  "org_humanoid_te_connectivity": "纽交所上市的连接器与传感器供应商候选。",
  "org_samsung_sdi": "韩国交易所上市的电池电芯供应商候选；股票代码 006400.KS 为韩国上市敞口，而非美国主上市。",
  "org_lg_energy_solution": "韩国交易所上市的电池电芯供应商候选；股票代码 373220.KS 为韩国上市敞口，而非美国主上市。",
  "org_catl": "深圳上市的电池电芯与电池包供应商候选；股票代码 300750.SZ 为中国大陆 A 股敞口，而非美国主上市。",
  "org_humanoid_gsa": "瑞士行星 / 卫星滚柱丝杠专家（Gewinde Satelliten Antriebe AG / Gewinde Ziegler AG，成立于 1982 年）。生产 RGTI 反式行星滚柱丝杠，被广泛报道为特斯拉为 Optimus 直线执行器采购的类型；建模为人形直线关节栈的近单一来源滚柱丝杠供应商候选。私营。",
  "org_humanoid_rollvis": "瑞士（日内瓦，成立于 1970 年）卫星 / 行星滚柱丝杠专家，以 “Rollvis Swiss” 经营；自称为卫星滚柱丝杠的世界领导者。与 GSA 一道，常被引述为占据高精度行星滚柱丝杠世界市场的多数份额——供给人形直线执行器的瑞士近单一来源环节。私营。",
  "humanoid_thread_grinding_equipment": "用于加工行星滚柱丝杠（及滚珠丝杠）亚 3 微米公差内外螺纹的超精密 CNC 螺纹磨床。这是瑞士滚柱丝杠环节背后的上游资本设备瓶颈：专门的内螺纹磨削专长与极少的合格磨床制造商共同制约着为人形直线执行器增加滚柱丝杠产能的速度。",
  "org_humanoid_drake_manufacturing": "美国（俄亥俄州 Warren）精密 CNC 螺纹与齿轮磨床制造商，产品包括面向滚珠丝杠与直线运动行业的内螺纹磨床及滚珠螺母 / 滚珠丝杠磨床——滚柱 / 滚珠丝杠生产背后的上游磨削设备层。私营。",
  "org_humanoid_ptg_holroyd": "英国高精度齿轮、转子、丝杠与螺纹铣磨设备制造商，宣称可生产世界上最精确的螺旋部件——是滚柱丝杠生产上游极少数超精密螺纹 / 丝杠磨床制造商之一。隶属 Precision Technologies Group；私营。",
  "org_humanoid_picea_motion": "深圳的精密谐波 / 应变波减速器厂商，前身为深圳市汉普士运动科技有限公司，更名为 PICEA Motion。被列为全球人形机器人谐波减速器关键制造商之一，也是 Harmonic Drive/Nabtesco 的中国国产替代方案。私营（部分行业来源称其为原大族激光子公司；公司自有网站则以独立公司形象呈现）。",
  "org_jl_mag_rare_earth": "双重上市（深圳 300748.SZ / 香港 06680.HK）的中国烧结钕铁硼永磁厂商；2025 年将其人形机器人磁性元件研发部门升级为专门事业部。磁体产出处于中国稀土出口许可制度之内。部件敞口候选；非确认的人形 BOM 配置。",
  "org_shin_etsu_chemical": "东京上市（4063.T）的钕铁硼（Nd-Fe-B）烧结稀土磁体（N 系列）制造商，用于工业伺服电机与直线电机；运营日本大规模稀土分离 / 精炼，并正建设重稀土精炼厂以摆脱对中国供应的依赖。部件敞口候选；非确认的人形 BOM 配置。",
  "org_proterial": "日本私营磁体 / 材料厂商（前身日立金属；2023 年经贝恩资本主导收购后更名），率先研发并量产用于电机的 NEOMAX 钕铁硼烧结磁体，并量产可最大限度减少镝 / 铽用量的省重稀土牌号。私营——无公开股票代码。部件敞口候选；非确认的人形 BOM 配置。",
  "org_regal_rexnord": "纽交所上市（RRX）的运动控制集团，旗下品牌包括 Kollmorgen（及通过 2023 年 Altra 交易收购的 Portescap）。Kollmorgen 无框 / 直驱力矩电机（TBM/KBM/TBM2G）面向机器人、协作机器人与人形关节。部件敞口候选；非确认的人形 BOM 配置。",
  "org_maxon": "瑞士私营精密驱动厂商；其 EC 无框 DT 力矩电机与集成高效关节（HEJ）执行器明确面向人形、四足与外骨骼。（亦为灵巧手提供空心杯 / 无铁芯微电机。）私营——无公开股票代码。部件敞口候选；非确认的人形 BOM 配置。",
  "org_humanoid_netzer": "以色列私营厂商，生产非接触式电容（Electric Encoder）绝对中空轴编码器；不受无框电机磁体附近磁干扰影响，用于人形 / 航天机器人臂关节（如 NASA Robonaut 2）。供应商候选。",
  "org_humanoid_novanta_ati": "美国纳斯达克上市的精密技术集团；其 ATI Industrial Automation 部门是长期在位的机器人力控多轴（六轴）力 / 力矩传感器制造商，是人形腕 / 手力-力矩传感的供应商候选。",
  "org_humanoid_bota_systems": "瑞士（苏黎世）私营厂商，为人形、医疗与协作机器人制造紧凑型 6 轴力 / 力矩传感器、扭矩传感器与触觉传感器（MiniONE、PixONE）。人形力-力矩 / 指尖传感的供应商候选。",
  "org_humanoid_sri_sunrise": "私营六轴力 / 力矩传感器与多轴测力计制造商（总部美国密歇根州 Canton；在中国制造），拥有专门的人形机器人 6 轴力 / 力矩传感器产品线（C025XX-C060XX）。供应商候选。",
  "org_humanoid_xela_robotics": "私营（早稻田大学衍生，东京）厂商，制造覆盖指尖、指节与手掌的 uSkin 高密度三轴触觉皮肤传感器，用于人形与工业机器人手 / 夹爪。人形触觉传感的供应商候选。",
  "org_humanoid_paxini": "中国私营厂商，生产多维触觉传感器（PX-6AX 系列，霍尔效应 6D 力 / 力矩）与触觉灵巧手（DexH13），面向人形 / 具身 AI 机器人；全栈触觉 + 手 + 机器人供应商候选。",
  "org_humanoid_bosch_sensortec": "罗伯特·博世（私营）的 MEMS 传感器子公司；高性能 IMU（BMI088、BMI323、BMI563）明确面向机器人，含敏捷人形与社交机器人。人形 IMU / 姿态传感的供应商候选。",
  "org_humanoid_hesai": "中国激光雷达厂商，双重上市于纳斯达克（HSAI）/ 港交所（2525）；JT 系列迷你 360° 3D 机器人激光雷达面向移动 / 人形机器人；是摩根士丹利 Humanoid Tech 25 名单中唯一的激光雷达公司。人形深度 / 激光雷达感知的供应商候选。",
  "org_humanoid_robosense": "中国激光雷达 / 机器人视觉厂商，港交所上市（2498.HK）；Active Camera（AC1/AC2）融合激光雷达 + RGB + IMU 视觉，并为人形机器人提供灵巧手；与多家人形公司合作。人形感知的供应商候选。",
  "org_humanoid_orbbec": "中国 3D 视觉相机厂商，上海科创板上市（688322.SS）；Gemini 系列立体视觉深度相机面向机器人 / 具身 AI（荣耀人形、Reachy 2；集成 Jetson Thor）；据报在中国服务机器人 / 韩国移动机器人的 3D 视觉份额超 70%。供应商候选。",
  "org_humanoid_realsense": "立体深度相机厂商，2025 年自英特尔分拆为独立私营公司（约 5000 万美元 A 轮，与 NVIDIA 合作）。D4xx 深度相机（如 Agility Digit 颈部的 D455）；据报与约 60% 的 AMR 与人形开发者合作。人形深度 / RGB 感知的供应商候选。",
  "org_eve_energy": "深圳上市（创业板）的锂离子与全固态电池电芯厂商；股票代码 300014.SZ 为中国大陆 A 股敞口，而非美国主上市。电芯商用供应商候选；人形电池包仍由集成商自研封闭。",
  "org_molicel": "超高功率圆柱锂离子电芯制造商；商用电芯供应商候选，其产品网站列有 “人形机器人应用”。未直接上市；股票代码 1101.TW 为其母公司台湾水泥（TCC）集团于台湾证券交易所，即间接母公司层面敞口，而非美国主上市。人形电池包仍由集成商自研封闭；Molicel 供应电芯。",
  "org_panasonic": "主要的高功率 / 高能量圆柱锂离子电芯制造商（2170 形制）。商用电芯供应商候选；股票代码 6752.T 为母公司松下控股于东京证券交易所（松下能源为其电池板块），即日本上市敞口，而非美国主上市。人形机器人复用此类高功率圆柱电芯；电池包仍由集成商自研封闭。",
  "org_infineon": "上市的功率半导体与微控制器厂商（功率开关 / MOSFET、栅极驱动、电池监控与均衡 IC、MCU）。人形功率电子 / BMS 前端的商用芯片供应商；股票代码 IFX.DE 为法兰克福 / Xetra 敞口（美国 OTC：IFNNY），而非美国主上市。供应商用 IC；BMS 控制固件 / 算法属机器人厂商（自研）。",
  "org_nxp": "纳斯达克上市（NXPI）的半导体厂商；供应电池管理 IC 与面向移动机器人（无人机 / 移动平台）的独立 BMS 参考设计，以及用于 BMS / 逆变器的 MCU。商用芯片供应商候选；电池包 BMS 固件 / 集成仍属机器人厂商。",
  "org_humanoid_qualcomm": "美国上市（纳斯达克）的机器人 SoC 供应商；推出 Dragonwing IQ10 系列高端机载 “机器人大脑” 处理器，面向全尺寸人形与 AMR，并与 Figure 就人形计算架构合作。是机载 AI 计算上 NVIDIA Jetson Thor 的商用替代方案。",
  "org_humanoid_rockchip": "中国上市（上海）的应用处理器 SoC 设计商；其 RK3588/RK3588S 边缘 SoC（八核，约 6 TOPS NPU）是多款中国人形机器人采用的主计算 / “大脑” 平台（如智元灵犀 X2、LimX Oli）。面向国产人形机器人的低成本机载计算替代方案，对标 NVIDIA Jetson Thor。",
  "org_humanoid_d_robotics": "地平线机器人（港交所：9660）私营持有的机器人芯片衍生公司（D-Robotics 与其共享技术血统并协调路线图，但为独立的 A 轮融资公司）。生产 RDK S100——业界首个将机器人 “大脑”（计算）与 “小脑”（控制）集成于单一 SoC 的平台，80-128 TOPS——面向人形机器人开发者。商用机载计算-控制 SoC。",
  "org_humanoid_epc": "私营（加州 El Segundo）氮化镓（GaN）功率半导体厂商；提供专为人形机器人关节应用设计的 EPC91122 三相 BLDC 电机驱动逆变器评估板，以及用于紧凑腕 / 指 / 趾电机的 GaN 器件。面向人形执行器的商用 GaN 电机驱动 / 栅极驱动-逆变器供应商。",
  "org_humanoid_microchip": "美国上市（纳斯达克）的微控制器与模拟供应商；其基于 dsPIC33 DSC 的集成电机驱动器将数字信号控制器、三相 MOSFET 栅极驱动与 LIN/CAN FD 合于一体，用于 FOC 的 BLDC/PMSM 电机控制。可用于人形关节 / 执行器驱动的商用电机驱动 MCU + 栅极驱动供应商（机器人 / 工业电机控制级，人形设计导入尚未确认）。",
  "org_humanoid_victrex": "伦敦上市的 PEEK 聚合物厂商（VICTREX PEEK / PAEK，HPG 齿轮）；全球约 4 家千吨级 PEEK 生产商之一。面向机器人齿轮、衬套 / 轴承及替代金属的轻量化部件推广 PEEK。PEEK 是人形骨架 / 肢体中标志性的轻量化聚合物。",
  "org_humanoid_evonik": "法兰克福上市的特种化学品厂商；VESTAKEEP PEEK 产品线（含摩擦学 Easy Slide 2 滑动轴承）明确面向机器人行业推广。全球约 4 家千吨级 PEEK 生产商之一。",
  "org_humanoid_sanhua": "深圳上市的汽车 / 暖通热管理厂商（微通道液冷、电子膨胀阀），被广泛报道为特斯拉 Optimus 的热 / 液冷及执行器供应商。注意：一份高质量来源指出三花当前的人形重点是机电执行器而非热系统——“Optimus 独家液冷供应商” 的说法源自 SEO/substack，此处未予确认。建模为据报有能力；需提请验证者复核。",
};
